openapi: 3.0.0
definitions:
  Candle:
    properties:
      close:
        description: Close price
        type: number
      date_open:
        description: Date open candle
        format: date
        type: string
      high:
        description: High price
        type: number
      low:
        description: Low price
        type: number
      open:
        description: Open price
        type: number
      volume:
        description: Volume
        type: number
    required:
      - date_open
    type: object
info:
  title: Yahoo quote loader service
  version: v1
paths:
  /api/quote:
    get:
      description: Get stock quotes
      parameters:
        - description: Yahoo stock code
          in: query
          name: stock
          required: true
          schema: 
            type: string
            example: "AAPL"
        - description: Timeframe
          in: query
          name: timeframe
          required: true
          schema: 
            type: string
            enum:
            - DAY
            - WEEK
            - MONTH
            - D
            - W
            - M
            example: DAY
        - description: Download from date
          in: query
          name: date_from
          required: true
          schema: 
            type: string
            format: date
            example: "2020-01-01"
        - description: Download till datea
          in: query
          name: date_till
          required: true
          schema: 
            type: string
            format: date
            example: "2021-01-01"
      responses:
        '200':
          description: 'Loaded stock quotes in candles'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/definitions/Candle'
                type: array
        '400':
          description: 'Error while loading'
          content:
            plain/text:
              schema:
                type: string
                example: "Stock XYZ doesn't found"
      tags:
        - Quotes

